Initial JHU DA Docker skeleton.
jhu-sheridan-libraries/jhuda-docker pull request #2
Opened 2019-11-26 16:08 UTC by emetsger

To test:

* Alias `archive.local` to your docker host
* Run `docker-compose pull`
* Run `docker-compose up -d`, wait for all services to start
* Access `https://archive.local/fcrepo/rest` from your browser
* Authenticate as `depositor`, password `moo`

2019-11-26 16:37 UTC, birkland requested changes
@emetsger Can you add the `.env` file?  It needs it in order to resolve, e.g. `FCREPO_PORT` in the `docker-compose.yml`

2019-11-28 14:03 UTC, emetsger commented
@birkland fixed a couple things with this PR.  I submitted it from my laptop which not only had the uncommitted `.env`, but it also had an out-of-date assets image tagged.  

The most recent commit updates all of the image tags.  The new images should contain `LABEL` statements with their GitHub provenance, making it a bit easier to see exactly what one is working with when there is an issue.

Happy Thanksgiving :)

2019-12-02 15:52 UTC, birkland approved these changes
Works!

2019-12-02 15:53 UTC, birkland approved these changes

2019-12-02 15:53 UTC, merged